/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciamentobiblioteca.Menu;

import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author camil
 */
public class TelaMain extends javax.swing.JFrame {

    public TelaMain() {
        initComponents();

        //setExtendedState(MAXIMIZED_BOTH); // abre maximizada

        //setSize(900, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLivros = new javax.swing.JMenu();
        jmCadastro = new javax.swing.JMenu();
        jmCadastroLivro = new javax.swing.JMenuItem();
        jmCadastroAutor = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenuItem();
        jmArquivos = new javax.swing.JMenu();
        arquivoLivro = new javax.swing.JMenuItem();
        arquivoQueroler = new javax.swing.JMenuItem();
        jmSobre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Livros");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Minha Estante Virtual");

        btnSair.setText("Sair");
        btnSair.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lendo-um-livro (1).png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/brilhante (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/brilhante (1).png"))); // NOI18N
        jLabel4.setText("jLabel3");

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jmLivros.setText("Livros");

        jmCadastro.setText("Cadastro");

        jmCadastroLivro.setText("Cadastro Livros");
        jmCadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroLivroActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroLivro);

        jmCadastroAutor.setText("Cadastro Quero ler");
        jmCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroAutorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroAutor);

        jmLivros.add(jmCadastro);

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jmLivros.add(jmSair);

        jMenuBar1.add(jmLivros);

        jmArquivos.setText("Arquivos");

        arquivoLivro.setText(".txt Livros");
        arquivoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoLivroActionPerformed(evt);
            }
        });
        jmArquivos.add(arquivoLivro);

        arquivoQueroler.setText(".txt Quero Ler");
        arquivoQueroler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivoQuerolerActionPerformed(evt);
            }
        });
        jmArquivos.add(arquivoQueroler);

        jMenuBar1.add(jmArquivos);

        jmSobre.setText("Sobre");
        jmSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSobreActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sobre o Sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmSobre.add(jMenuItem1);

        jMenuBar1.add(jmSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        dispose();
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmCadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroLivroActionPerformed
        TelaCadastroLivro tela = new TelaCadastroLivro();
        tela.setVisible(true);
    }//GEN-LAST:event_jmCadastroLivroActionPerformed

    private void jmCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroAutorActionPerformed
        TelaCadastroQueroLer tela = new TelaCadastroQueroLer();
        tela.setVisible(true);
    }//GEN-LAST:event_jmCadastroAutorActionPerformed

    private void arquivoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoLivroActionPerformed
        try {
            File arquivo = new File("livro.txt"); 

            if (!arquivo.exists()) {
                JOptionPane.showMessageDialog(this, "O arquivo livro.txt ainda não existe!");
                return;
            }

            Desktop.getDesktop().open(arquivo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir arquivo: " + e.getMessage());
        }
    }//GEN-LAST:event_arquivoLivroActionPerformed

    private void arquivoQuerolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoQuerolerActionPerformed
        try {
            File arquivo = new File("queroLer.txt");

            if (!arquivo.exists()) {
                JOptionPane.showMessageDialog(this, "O arquivo genero.txt ainda não existe!");
                return;
            }

            Desktop.getDesktop().open(arquivo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir arquivo: " + e.getMessage());
        }
    }//GEN-LAST:event_arquivoQuerolerActionPerformed

    private void jmSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSobreActionPerformed

    }//GEN-LAST:event_jmSobreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaSobre tela = new TelaSobre();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem arquivoLivro;
    private javax.swing.JMenuItem arquivoQueroler;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmArquivos;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCadastroAutor;
    private javax.swing.JMenuItem jmCadastroLivro;
    private javax.swing.JMenu jmLivros;
    private javax.swing.JMenuItem jmSair;
    private javax.swing.JMenu jmSobre;
    // End of variables declaration//GEN-END:variables
}
